######################################################################
##  start off all weekdays at 05:50am except if vacation or via Good Morning signal
######################################################################

- alias: 'Lights turn on at 05.50 or via good morning signal'
  trigger:
    - platform: time
      at: '05:50:00'
    - platform: state
      entity_id: input_boolean.good_morning
      to: 'on'
      from: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.good_morning
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: sensor.someone_home
            state: 'yes'
          - condition: state
            entity_id: input_boolean.vacation_mode
            state: 'off'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
  action:
  #  - service: script.morning_lights
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.night_mode
        - input_boolean.good_morning
    - service: switch.turn_on
      entity_id:
        - switch.window_kitchen
        - switch.window_dinner_room
        - switch.window_laundry
        - switch.wall_dinner_room
        - switch.wall_main_room
    - service: light.turn_on
      entity_id:
        - light.hallway_1
        - light.hallway_2
      data_template:
        brightness: "{{ states('sensor.time_brightness')|int }}"
        color_temp: "320"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - service: light.turn_on
      entity_id:
        - light.window_office
      data_template:
        brightness: "{{ states('sensor.time_brightness')|int }}"
    - delay: '00:30:00'
    - service: light.turn_on
      entity_id:
        - light.interior_philip_room
      data_template:
        brightness: "{{ states('sensor.time_brightness')|int }}"
        color_temp: "320"
