######################################################################
##  Stuff that needs to happen at 05:50am.
######################################################################

- alias: 'Timed 550.'
  trigger:
    - platform: time
      at: '05:50:00'
    - platform: state
      entity_id: input_boolean.good_morning
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: sensor.someone_home
      state: 'yes'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.morning_lights
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - service: switch.turn_on
      entity_id: switch.window_office
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_mode
