# Turn off house when going to bed
- alias: Turn off house when going to bed
  trigger:
    # - platform: state
    #   entity_id: sensor.petersiphone_battery_state
    #   from: "Unplugged"
    #   to: "Charging"
    - platform: state
      entity_id: input_boolean.good_night
      to: 'on'
      from: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.someone_home
        state: 'yes'
      - condition: sun
        after: sunset
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.window_lights
    - delay: 00:00:20
    - service: homeassistant.turn_off
      entity_id:
        - group.window_main_room_lights
    - service: homeassistant.turn_off
      entity_id:
        - group.interior_lights
    - delay: 00:00:20
    - service: homeassistant.turn_off
      entity_id:
        - group.wall_lights
    - delay: 00:00:20
    - service: homeassistant.turn_off
      entity_id:
        - group.ceiling_lights
    - service: input_boolean.turn_on
      entity_id: input_boolean.night_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night
