# Turn off house when going to bed
- alias: Turn off house when going to bed
  trigger:
    - platform: state
      entity_id: input_boolean.good_night
      to: 'on'
      from: 'off'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      data:
        entity_id: light.wall_dinner_room
        flash: 'short'
    - service: input_boolean.turn_on
      entity_id: input_boolean.night_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night
    - service: script.lights_off
