###################################
##  Sunrise events
###################################

- alias: 'Turn on exterior lights before Sunrise'
  trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'
    - platform: time
      at: '06:00:00'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
#    - service: script.interior_off
    - service: homeassistant.turn_on
      entity_id:
        - group.exterior_lights
      data:
        brightness: 100

###################################
##  Sunrise events
###################################

- alias: 'Turn off exterior lighgts when Sunrise'
  trigger:
    - platform: sun
      event: sunrise
  action:
#    - service: script.interior_off
    - service: homeassistant.turn_off
      entity_id:
        - group.exterior_lights
