###################################
##  Sunrise events
###################################

- alias: 'Sunrise events'
  trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'

  action:
#    - service: script.interior_off
    - service: homeassistant.turn_on
      entity_id:
        - group.exterior_lights

    # - delay: '00:{{ (range(1, 55)|random|int) }}:00'
    # - service: light.turn_off
    #   entity_id:
    #     - group.exterior_lights
    #     - group.outdoor_front_lights
    #     - group.outdoor_pool_lights
    #     - group.all_lights

    - wait_template: >-
       {{ states.sun.sun.state == 'above_horizon' }}
    - service: homeassistant.turn_off
      entity_id:
        - group.morning_lights
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - service: switch.turn_off
      entity_id:
        - switch.window_office
    - service: homeassistant.turn_off
      entity_id:
        - group.exterior_lights
    - service: input_boolean.turn_off
      entity_id:
        # - input_boolean.medicine
        # - input_boolean.daylight_override
        - input_boolean.night_mode
        - input_boolean.guest_mode
