# Turn on lights in Garage when door is open, and send text if noone is home
- alias: Turn ON Garage Lights when door is open
  initial_state: true
  trigger:
    - platform: template
      value_template: "{% if is_state('binary_sensor.garage_door', 'on') %}true{% endif %}"
  condition:
    - condition: state
      entity_id: sensor.someone_home
      state: 'yes'
    # - condition: state
    #   entity_id: sun.sun
    #   state: 'below_horizon'
  action:
    - service: script.garage_lights_timer

#   alias: door_open
#   trigger:
#     platform: state
#     entity_id: binary_sensor.garagedorren
#     to: 'on'
#   action:
#     service_template: >
#       {% if is_state('sensor.someone_home','yes')%}
#         homeassistant.turn_on
#       {% else %}
#         notify.ios_petersiphone
#       {% endif %}
#
#     data_template: >
#       {% if is_state('sensor.someone_home','yes')%}
#         switch.tak_garage
#       {% else %}
#         message: "Garage door is open!
#       {% endif %}
