# Turn on lights in Garage when door is open
- alias: Turn ON Garage Lights when door is open
  initial_state: true
  trigger:
    - platform: template
      value_template: "{% if is_state('binary_sensor.garage_door', 'on') %}true{% endif %}"
  condition:
    - condition: state
      entity_id: sensor.someone_home
      state: 'yes'
  action:
#    - service: script.garage_lights_timer
    - service: timer.start
      entity_id: timer.timer_garage
    - service: light.turn_on
      entity_id:
        - light.ceiling_garage

- alias: Turn OFF Garage Lights when door is closed
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_garage
  action:
#    - wait_template: "{{ states.binary_sensor.garage_door == 'off'}} "
      # timeout: '00:01:45'
      # continue_on_timeout: 'true'
    - service: light.turn_off
      entity_id:
        - light.ceiling_garage
