#Turn on inside lights when noone is home and sun gone down
- alias: Turn on inside light when sun sets
  initial_state: true
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: sensor.someone_home
      state: 'no'
  action:
    service: light.turn_on
    entity_id:
    - light.interior_lights
    - light.wall_lights

# Turn the inside lights off when noone is home
- alias: Lights off inside
  initial_state: true
  trigger:
    platform: time
    at: '22:35:00'
  condition:
    - condition: state
      entity_id: sensor.someone_home
      state: 'no'
  action:
    service: light.turn_off
    entity_id:
    - light.interior_lights
    - light.wall_lights
