- alias: 'Turn on interior lights when someone gets home'

  trigger:
    - platform: state
      entity_id: sensor.someone_home
      from: 'no'
      to: 'yes'

  action:
    - service_template: >-
        {% if is_state ("sensor.light_sensor", "Shade") %}
          script.shade_lights
        {% elif is_state ("sensor.light_sensor", "Bright") %}
          script.bright_lights
        {% elif is_state ("sensor.light_sensor", "Dim") %}
          script.dim_lights
        {% elif is_state ("sensor.light_sensor", "Dark") %}
          script.dark_lights
        {% endif %}



# - alias: 'People Greeting'
#
#   trigger:
#     - platform: state
#       entity_id:
#         - sensor.location_peter
# #        - device_tracker.carlo
# #        - device_tracker.stacey
# #        - device_tracker.franco
# #        - device_tracker.yolanda
#       from: 'not_home'
#       to: 'home'
#       for: '00:02:00'
#
#   action:
#     - service: media_player.turn_on
#       entity_id: media_player.marantzsr5007
#     - service: media_player.volume_set
#       entity_id:
#         - media_player.marantzsr5005
#       data_template:
#         volume_level: >
#           {% if now().strftime("%H")|int < 12 and now().strftime("%H")|int > 6%}
#           0.3
#           {% elif now().strftime("%H")|int > 12 and now().strftime("%H")|int < 20%}
#           0.5
#           {% else %}
#           0.3
#           {% endif %}
#     - delay: 00:00:10
#     # - service: tts.google_say
#     #   entity_id: media_player.marantzsr5007
#     #   data_template:
#     #     message: 'Hello, welcome peter'
#     - delay: 00:00:10
#     - service: media_player.turn_off
#       entity_id: media_player.marantzsr5007
