- alias: 'Toggle Philip Room lamps from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 1002
  action:
    service: light.toggle
    entity_id:
      - light.ceiling_philip_room
      - light.interior_philip_room
<<<<<<< HEAD
    data:
      rgb_color: [255,0,191]

- alias: 'Set full brightness for Philip Room'
=======

- alias: 'Increase brightness of Philip Room lamps'
>>>>>>> 35639dc9f0964ac079486b3d9f1918ad74eb7f9b
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
<<<<<<< HEAD
        brightness: 254
        rgb_color: [255,255,255]

- alias: 'Restore color and brightness for Philip Room lamps'
=======
        brightness: {% raw %}>
          {% set bri = states.light.lamp.attributes.brightness | int %}
          {{ [bri+30, 249] | min }}{% endraw %}
        rgb_color: [255,255,255]

- alias: 'Decrease brightness of Philip Room lamps'
>>>>>>> 35639dc9f0964ac079486b3d9f1918ad74eb7f9b
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
<<<<<<< HEAD
      id: philip_remote
=======
      id: remote_control_1
>>>>>>> 35639dc9f0964ac079486b3d9f1918ad74eb7f9b
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
<<<<<<< HEAD
        brightness: "{{ states('sensor.time_brightness')|int }}"
        rgb_color: [255,0,191]
=======
        brightness: {% raw %}>
          {% set bri = states.light.lamp.attributes.brightness | int %}
          {{ [bri-30, 0] | max }}{% endraw %}
        rgb_color: [255,255,255]
>>>>>>> 35639dc9f0964ac079486b3d9f1918ad74eb7f9b
