- alias: 'Toggle Philip Room lamps from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 1002
  action:
    - service: light.toggle
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
    - service: switch.toggle
      data_template:
        entity_id:
          - switch.x_mas_philip


- alias: 'Set full brightness for Philip Room'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
        brightness: 255
        color_temp: "239"

- alias: 'Restore color and brightness for Philip Room lamps'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
        brightness: "{{ states('sensor.time_brightness')|int }}"
        color_temp: "320"

- alias: 'Red color brightness for Philip Room lamps'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 4002
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
        brightness: 254
        rgb_color: [255,0,0]

- alias: 'Purple color brightness for Philip Room lamps'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 4001
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
        brightness: 254
        rgb_color: [255,0,191]

- alias: 'Random Loop for Philip Room lamps'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philip_remote
      event: 5002
  action:
    - service: light.turn_on
      data_template:
        entity_id:
          - light.ceiling_philip_room
          - light.interior_philip_room
        brightness: 254
        effect: 'LSD'
