###############################################################################################################
# Template
- platform: template
  sensors:

############################################################
#
# Someone home
#
############################################################

    someone_home:
      value_template: >
        {% if is_state("group.location_katarina", "home") or is_state("group.location_peter", "home") or is_state("group.location_philip", "home") or is_state("input_boolean.guest_mode", "on")%}
          yes
        {% else %}
          no
        {% endif %}


############################################################
#
# Christmas Period
#
############################################################

    christmas_period:
      value_template: >
        {% if (is_state ("light.window_kitchen","unavailable") and is_state("light.window_dinner_room", "unavailable") and ( (now().month == 12) or (now().month == 1))  ) %}
          yes
        {% else %}
          no
        {% endif  %}
        
############################################################
#
# Set brightness depending on Time of Day
#
############################################################

    time_brightness:
      value_template: >-
            {%- if now().strftime('%H%M')|int < 600 -%}
              32
            {%- elif now().strftime('%H%M')|int < 700 -%}
              96
            {%- elif now().strftime('%H%M')|int < 900 -%}
              128
            {%- elif now().strftime('%H%M')|int < 1100 -%}
              160
            {%- elif now().strftime('%H%M')|int < 1400 -%}
              200
            {%- elif now().strftime('%H%M')|int < 2000 -%}
              160
            {%- elif now().strftime('%H%M')|int < 2230 -%}
              128
            {%- elif now().strftime('%H%M')|int < 2330 -%}
              96
            {%- else -%}
              32
            {%- endif -%}
      entity_id: []

###########################################################
#
# Set Light Sensor to brightness for Automations
#
############################################################

    light_sensor:
      friendly_name: Inside Light Sensor
      value_template: >-
        {% if states("sensor.luminance_dinner_room_mean") | float >= 50.0 %}
          Bright
        {% elif states("sensor.luminance_dinner_room_mean") | float < 50.0 and states("sensor.luminance_dinner_room_mean") | float >= 40.0 %}
          Dim
        {% elif states("sensor.luminance_dinner_room_mean") | float < 40.0 and states("sensor.luminance_dinner_room_mean") | float >= 25.0 %}
          Shade
        {% elif states("sensor.luminance_dinner_room_mean") | float < 25.0 and is_state("input_boolean.night_mode", "off") %}
          Dark
        {% elif states("sensor.luminance_dinner_room_mean") | float < 25.0 and is_state("input_boolean.night_mode", "on") %}
          Night
        {% else %}
          unknown
        {% endif %}
