- platform: mqtt
  devices:
    peter_iphone_bt: 'location/peter_bt'
    katarina_iphone_bt: 'location/katarina_bt'
    philip_galaxys6_bt: 'location/philip_bt'
  source_type: bluetooth
  track_new_devices: true
