- platform: rfxtrx
  automatic_add: false
  devices:
    0b11000d007cc0fa02000070:
      name: Ceiling Dinner room

- platform: group
  name: Window Kitchen
  entities:
    - light.window_kitchen_1
    - light.window_kitchen_2

- platform: group
  name: Window Main Room
  entities:
    - light.window_main_room_1
    - light.window_main_room_2

- platform: group
  name: Hallway
  entities:
    - light.hallway_1
    - light.hallway_2

- platform: group
  name: Exterior Garage
  entities:
    - light.ExtG1D
    - light.ExtG1U
    - light.ExtG2D
    - light.ExtG2U

- platform: group
  name: Exterior Garage Up
  entities:
    - light.ExtG1U
    - light.ExtG2U

- platform: group
  name: Exterior Garage Down
  entities:
    - light.ExtG1D
    - light.ExtG2D


- platform: yeelight
  devices:
    192.168.1.147:
      name: Interior Main Room
      # transition: 1000
      # use_music_mode: True #(defaults to False)
      # save_on_change: False #(defaults to True)
    192.168.1.148:
      name: Interior Philip Room

    192.168.1.149:
      name: Ceiling Philip Room
    192.168.1.150:
      name: Ceiling Porch
