- platform: rfxtrx
  automatic_add: false
  devices:
    0b11000d007cc0fa02000070:
      name: Ceiling Dinner room

- platform: group
  name: Window Kitchen
  entities:
    - light.window_kitchen_1
    - light.window_kitchen_2

- platform: group
  name: Window Main Room
  entities:
    - light.window_main_room_1
    - light.window_main_room_2

- platform: group
  name: Hallway
  entities:
    - light.hallway_1
    - light.hallway_2

- platform: group
  name: Exterior Garage
  entities:
    - light.ExtG1D
    - light.ExtG1U
    - light.ExtG2D
    - light.ExtG2U

- platform: group
  name: Exterior Garage Up
  entities:
    - light.ExtG1U
    - light.ExtG2U

- platform: group
  name: Exterior Garage Down
  entities:
    - light.ExtG1D
    - light.ExtG2D

- platform: group
  name: Exterior Storage
  entities:
    - light.ExtS1D
    - light.ExtS1U

- platform: group
  name: Exterior Post
  entities:
    - light.ExtPost1
    - light.ExtPost2
    - light.ExtPost3

- platform: group
  name: Exterior Back Up
  entities:
    - light.ExtB1U
    - light.ExtB2U
    - light.ExtB3U

- platform: group
  name: Exterior Back Down
  entities:
    - light.ExtB1D
    - light.ExtB2D
    - light.ExtB3D

- platform: group
  name: Exterior Back
  entities:
    - light.ExtB1D
    - light.ExtB1U
    - light.ExtB2D
    - light.ExtB2U
    - light.ExtB3U
    - light.ExtB3D

- platform: group
  name: Exterior Front Up
  entities:
    - light.ExtF2U
    - light.ExtF3U

- platform: group
  name: Exterior Front Down
  entities:
    - light.ExtF2D
    - light.ExtF3D

- platform: group
  name: Exterior Front
  entities:
    - light.ExtF1
    - light.ExtF2D
    - light.ExtF2U
    - light.ExtF3U
    - light.ExtF3D

- platform: group
  name: Exterior BackSide
  entities:
    - light.ExtBS1D
    - light.ExtBS1U
    - light.ExtBS2D
    - light.ExtBS2U

- platform: group
  name: Exterior BackSide Up
  entities:
    - light.ExtBS1U
    - light.ExtBS2U

- platform: group
  name: Exterior BackSide Down
  entities:
    - light.ExtBS1D
    - light.ExtBS2D

- platform: yeelight
  devices:
    192.168.1.147:
      name: Interior Main Room
      # transition: 1000
      # use_music_mode: True #(defaults to False)
      # save_on_change: False #(defaults to True)
    192.168.1.148:
      name: Interior Philip Room

    192.168.1.149:
      name: Ceiling Philip Room
    192.168.1.150:
      name: Ceiling Porch
