- platform: lg_netcast
  host: !secret media_player_lgtv
  access_token: !secret media_player_lgtv_token
# - platform: denonavr
#   host: !secret media_player_marantz
#   show_all_sources: true
- platform: denonavr
  host: !secret media_player_mainroom
  show_all_sources: true
# - platform: plex
#   entity_namespace: 'plex-ds'

- platform: spotify
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

# Coffey Table Jazz
# spotify:user:spotify:playlist:37i9dQZF1DWVqfgj8NZEp1
#
# Digster Soft Jazz
# spotify:perese:digster.se:playlist:33YLYbQcmFT7Qv7NrNVIDo
#
# New Music Friday
# spotify:user:spotify:playlist:37i9dQZF1DXcecv7ESbOPu
#
# Girl PWR
# spotify:user:spotify:playlist:37i9dQZF1DX3JcVtdd4I4E
# https://open.spotify.com/playlist/7jvC4zj4QPYtEi1dpJ0m94
