- platform: broadlink
  host: 192.168.1.151
  mac: '34:EA:34:42:A6:89'
  timeout: 15
  switches:
    tv_lg:
      friendly_name: "LG Tv Power"
      command_on: 'JgB4AAABKZISExITEjcTExETEhMSExITEjcSNxMTEjcSNxM3EjcTNxMTEhISExI3ExMSEhITEhMSNxM2EzcTExI2EzcTNxI3EwAFJgABKUkSAAxWAAEpSRIADFYAASlJEgAMVgABKUkSAAxWAAEpSRIADFYAASlJEgANBQ=='
      command_off: 'JgB4AAABKZISExITEjcTExETEhMSExITEjcSNxMTEjcSNxM3EjcTNxMTEhISExI3ExMSEhITEhMSNxM2EzcTExI2EzcTNxI3EwAFJgABKUkSAAxWAAEpSRIADFYAASlJEgAMVgABKUkSAAxWAAEpSRIADFYAASlJEgANBQ=='


- platform: rfxtrx
  automatic_add: false
  signal_repetitions: 3
  devices:
#    0b1100010128d6d60a000070:
#      name: Altandörren
#    0913000907e426019370:
#      name: Badrumsdörren
#    0b11000d007cc0fa0a000070:
#      name: Entrédörren
    0b11000d007cc0fa01000070:
      name: Engine Heater
    # 0b11000d03F243FE01000070:
    #   name: Window Office
    # 0b11000d03F243FE02000070:
    #   name: Interior Main room
    0b11000d03F243FE03000070:
      name: Front Door Hallway
    0b11000d03F243FE04000070:
      name: Wall Fire Place
    0b11000d03F243FE05000070:
      name: Window Kitchen
    0b11000d03F243FE06000070:
      name: Window Philip
    # 0b11000d03F243FE07000070:
    #   name: Window Master Bedroom
    0b11000d03F243FE08000070:
      name: Exterior post
    0b11000d03F243FE09000070:
      name: Window Laundry
    0b11000d03F243FE0a000070:
      name: Wall Main room
    0b11000d03F243FE0f000070:
      name: Window dinner room
    # 0b11000d03F243FE10000070:
    #   name: Interior dinner room
    0b11000d007cc0fa04000070:
      name: Ceiling Garage
    0b11000d03F243FE0e000070:
      name: Ceiling Laundry
    0b11000d007cc0fa03000070:
      name: Interior Laundry
    0b11000d03F243FE0b000070:
      name: Wall dinner Room
    0b11000d007cc0fa05000070:
      name: Exterior Side Entry
    0b11000d007cc0fa06000070:
      name: Exterior Garage
