- platform: broadlink
  host: 192.168.1.151
  mac: '34:EA:34:42:A6:89'
  timeout: 15
  switches:
    tv_lg:
      friendly_name: "LG Tv Power"
      command_on: 'JgB4AAABKZISExITEjcTExETEhMSExITEjcSNxMTEjcSNxM3EjcTNxMTEhISExI3ExMSEhITEhMSNxM2EzcTExI2EzcTNxI3EwAFJgABKUkSAAxWAAEpSRIADFYAASlJEgAMVgABKUkSAAxWAAEpSRIADFYAASlJEgANBQ=='
      command_off: 'JgB4AAABKZISExITEjcTExETEhMSExITEjcSNxMTEjcSNxM3EjcTNxMTEhISExI3ExMSEhITEhMSNxM2EzcTExI2EzcTNxI3EwAFJgABKUkSAAxWAAEpSRIADFYAASlJEgAMVgABKUkSAAxWAAEpSRIADFYAASlJEgANBQ=='
      # Will work on most LG TVs
    tv_lg_hdmi1_hdmi2:
      friendly_name: "LG Tv HDMI12"
      command_on: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      command_off: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
    tv_lg_hdmi3:
      friendly_name: "LG Tv HDMI3"
      command_on: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='
    tv_lg_av1_av2:
      friendly_name: "LG Tv AV12"
      command_on: 'JgBIAAABIpQPFBITETgSEw8UEhQSEhEVDzgSOBAUETgQOQ84EjgRNxITETgSExA5EDgREhI3EhMROBMSEDkQFBETEjYTEhE4EQANBQ=='
      command_off: 'JgBIAAABH5YPFBETETgUERAUEBURFBATETgROBEUETcSNxE4ETcSOBISEBUQFREUEjUSFBA5ETcRNxE4ETkQOBAUEjcRFRAUEQANBQ=='

- platform: rfxtrx
  automatic_add: false
  signal_repetitions: 3
  devices:
    0b11000d03F243FE01000070:
      name: x_mas_office
    0b11000d03F243FE06000070:
      name: x_mas_philip
    0b11000d03F243FE07000070:
      name: x_mas_master_bedroom
    0b11000d03F243FE0f000070:
      name: x_mas_dinner_room
    0b11000d03F243FE05000070:
      name: x_mas_kitchen
    0b11000d03F243FE03000070:
      name: x_mas_main_room
    0b11000d03F243FE10000070:
      name: x_mas_tree
#    0b1100010128d6d60a000070:
#      name: Altandörren
#    0913000907e426019370:
#      name: Badrumsdörren
#    0b11000d007cc0fa0a000070:
#      name: Entrédörren
    # 0b11000d007cc0fa01000070:
    #   name:
    # 0b11000d03F243FE02000070:
    #   name: Interior Main room
    0b11000d03F243FE04000070:
      name: Wall Fire Place
    0b11000d03F243FE08000070:
      name: Engine Heater
    0b11000d03F243FE09000070:
      name: Window Laundry
    0b11000d03F243FE0a000070:
      name: Wall Main room
    0b11000d007cc0fa04000070:
      name: Ceiling Garage
    # 0b11000d03F243FE0e000070:
    #   name: Ceiling Laundry
    0b11000d007cc0fa03000070:
      name: Interior Laundry
    # 0b11000d03F243FE0b000070:
    #   name: Wall dinner Room
    #0b11000d007cc0fa05000070:
    #  name: Exterior Side Entry
    # 0b11000d007cc0fa06000070:
    #   name: Exterior Garage
