- platform: yeelight
  devices:
    192.168.1.147:
      name: Interior Main Room
      # transition: 1000
      # use_music_mode: True #(defaults to False)
      # save_on_change: False #(defaults to True)
    192.168.1.148:
      name: Interior Philip Room

    192.168.1.149:
      name: Ceiling Philip Room
    192.168.1.150:
      name: Ceiling Porch
