#####################################################################
#    @package          :     krisinformation
#    @description      :     krisinformation
#####################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'krisinfo'

      hidden: &hidden
        <<: *customize
        hidden: true

sensor:
  - platform: krisinformation
    name: Krisinformation Uppsala
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude
    radius: 50


automation:
  - alias: 'Krisinformation Alert'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.krisinformation_uppsala
      to: "Alert"
    action:
      - service: notify.ios_petersiphone
        data_template:
          message: >
            {{states.sensor.krisinformation_uppsala.attributes.messages[0].Headline}} - {{states.sensor.krisinformation_uppsala.attributes.messages[0].Message}} {{states.sensor.krisinformation_uppsala.attributes.messages[0].Web}}
